# Generated by Django 4.1.2 on 2022-11-28 16:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.CharField(max_length=10, unique=True)),
                ('CourseName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Year', models.IntegerField()),
                ('Month', models.IntegerField()),
                ('TotalWorkingHours', models.IntegerField()),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tareportsystem.course', to_field='CourseID')),
                ('LecturerID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tareportsystem.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.CharField(max_length=20, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('TASA', models.CharField(max_length=2)),
                ('Nationality', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReportHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('WorkCategory', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('Start', models.TimeField()),
                ('End', models.TimeField()),
                ('Break', models.DurationField()),
                ('WorkingHours', models.DurationField()),
                ('ReportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareportsystem.report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='StudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareportsystem.student', to_field='StudentID'),
        ),
    ]
