# Generated by Django 4.1.2 on 2022-11-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareportsystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportHours',
            new_name='ReportHour',
        ),
    ]
