# Generated by Django 4.1.2 on 2022-11-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareportsystem', '0002_rename_reporthours_reporthour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Nationality',
        ),
        migrations.AddField(
            model_name='student',
            name='WorkingPermitStatus',
            field=models.CharField(choices=[('Japanese', 'Japanese'), ('International', 'International')], default='Japanese', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='TotalWorkingHours',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='reporthour',
            name='WorkCategory',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1'),
        ),
        migrations.AlterField(
            model_name='student',
            name='TASA',
            field=models.CharField(choices=[('TA', 'TA'), ('SA', 'SA')], default='SA', max_length=2),
        ),
    ]
