# Generated by Django 4.1.2 on 2022-12-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareportsystem', '0004_alter_report_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Lecturer',
            field=models.ManyToManyField(to='tareportsystem.lecturer'),
        ),
        migrations.AddField(
            model_name='course',
            name='TASA',
            field=models.ManyToManyField(to='tareportsystem.student'),
        ),
    ]
