# Generated by Django 4.1.2 on 2022-12-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareportsystem', '0005_course_lecturer_course_tasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
