# Generated by Django 4.1.2 on 2022-12-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareportsystem', '0009_alter_report_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporthour',
            name='WorkCategory',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=5),
        ),
    ]
