# Generated by Django 4.1.2 on 2022-12-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareportsystem', '0010_alter_reporthour_workcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporthour',
            old_name='ReportID',
            new_name='ReportTitle',
        ),
    ]
