# Generated by Django 4.1.2 on 2022-12-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareportsystem', '0011_rename_reportid_reporthour_reporttitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CourseID',
            field=models.CharField(max_length=10, unique=True, verbose_name='Course ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseName',
            field=models.CharField(max_length=100, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='report',
            name='TotalWorkingHours',
            field=models.DurationField(verbose_name='Total Working Hours'),
        ),
        migrations.AlterField(
            model_name='reporthour',
            name='WorkCategory',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=5, verbose_name='Work Category'),
        ),
        migrations.AlterField(
            model_name='reporthour',
            name='WorkingHours',
            field=models.DurationField(verbose_name='Working Hours'),
        ),
        migrations.AlterField(
            model_name='student',
            name='StudentID',
            field=models.CharField(max_length=20, unique=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='WorkingPermitStatus',
            field=models.CharField(choices=[('Japanese', 'Japanese'), ('International', 'International')], default='Japanese', max_length=20, verbose_name='Working Permit Status'),
        ),
    ]
