# Generated by Django 4.1.2 on 2022-12-06 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareportsystem', '0013_alter_reporthour_reporttitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='CourseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tareportsystem.course', to_field='CourseID', verbose_name='Course ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='StudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareportsystem.student', to_field='StudentID', verbose_name='Student ID'),
        ),
    ]
